### PR TITLE
[tvOS] Add target to use blur on tvOS

### PR DESCRIPTION
**Pull request by JulienKode**
Add tvOS target to use react native blur on tvOS 😊

### CODE REVIEW

**Comment by Kureev** [comment]
Oh, so nice! Thank you so much!

**Comment by JulienKode** [comment]
@Kureev Awesome project 👍

**Comment by Kureev** [comment]
Glad you like it ❤️

**Comment by Kureev** [comment]
I just bumped version 3.0.0-alpha to 3.0.0, so you can use new target straight away!

**Comment by JulienKode** [comment]
@Kureev Thank you so much ! 👍

**Pull request merged**
