### PR TITLE
Update `rnpm` to `react-native link`

### PR DESCRIPTION
**Pull request by Baransu**
Updating documentation according to #118

### CODE REVIEW

**Comment by Kureev** [comment]
Can you please add a name of the plugin in the end? Otherwise, `react-native link` will try to link all native plugins in the system

**Comment by Baransu** [comment]
Right, I forgot about it at first place :)

**Comment by Kureev** [comment]
Thanks for the fast fix! 👍

**Comment by Baransu** [comment]
@Kureev I guess you can close #118 too :)

**Pull request merged**
