### PR TITLE
Changed the iOS deployment target from 9.0 to 7.0 so that its compatible with the default setting for react-native projects

### PR DESCRIPTION
**Pull request by npomfret**
Changed the iOS deployment target from 9.0 to 7.0 so that its compatible with the default setting for react-native projects

### CODE REVIEW

**Comment by Kureev** [comment]
UIVisualEffectView (native implementation for iOS part relies on it) is available in iOS8+. We can change it to 8, but I don't see any benefits of it.

**Comment by npomfret** [comment]
Ok, sorry - didn't realise that.  But changing it to 8 would be good - I'm just trying to get rid of bogus warnings in my build so I can focus not the real ones.

**Comment by Kureev** [comment]
Ok, I have no objections to merge it if you change it to 8

**Comment by npomfret** [comment]
https://github.com/react-native-community/react-native-blur/pull/75

**Pull request closed without merging**
