### PR TITLE
[WIP] Use UIViewPropertyAnimator for adjusting blurRadius

### PR DESCRIPTION
**Pull request by eliperkins**
apr-07-2017 19-45-07

UIVisualEffectView's `effect` property allows for animation using
UIViewPropertyAnimator. By leveraging this, we can have adjustments of
"blur radius" without using KVC on private APIs.

This is only available for iOS 10. Behavior is unchanged for iOS 9.

Based on feedback from #168.

### CODE REVIEW

**Comment by Kureev** [comment]
Can you please solve a conflict here?

**Comment by eliperkins** [comment]
I'm running into some issues with this approach when it comes to setting a different `blurType` and adjusting the values from there.

Since we're animating over the retained views, our animations are referencing view properties (namely, referencing `effect`) which contains a longer valid property.

I played around with setting up and tearing down views again, so that the references in the animation are correct, but this leads to some inconsistencies as well...

I'd love it if someone else pulled this down and played around with it before I'd call this ready to go.

**Comment by Kureev** [comment]
Should we re-create the view if we receive `nextProps.blurType !== props.blurType`?
Maybe I'm wrong, but we can re-create a view with custom `blurType` at the moment we update this prop. Wdyt, @eliperkins?

**Comment by eliperkins** [comment]
I'm not quite happy with how this turned out, so I'm going to close this in favor of #183 and then work on top of that...

**Pull request closed without merging**
