### PR TITLE
Added Support for RN 0.60.0

### PR DESCRIPTION
**Pull request by thedeepanshujain**
# Summary

Added Support for RN 0.60.0 including Android X

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by aqmebrak** [comment]
This should fix #310

**Comment by denissb** [comment]
Shouldn't we get this merged?

**Comment by Ericky14** [comment]
When is this PR getting merged?

**Comment by synapseradio** [comment]
This would be very useful to my team, would love to see it get merged - this would resolve some important build issues for us

**Comment by darran-kelinske-fivestars** [comment]
What else do we need to do to get this merged?

**Comment by valentinjob** [comment]
This issue blocks our release, anyway to merge it?

**Comment by wilau2** [comment]
We disabled blur in our app in order to release 😢

**Comment by timothystewart6** [comment]
Hi.  Just checking in to see if there is anything anyone can help with to get this released.

**Comment by msand** [comment]
I could merge it but probably don't have publish rights to npm, @grabbou @cpojer Could one of you handle it?

**Comment by cpojer** [comment]
@msand you should have rights to publish on @react-native-community.

**Comment by msand** [comment]
Ah, alright, great :) Thanks for handling it!

**Comment by msand** [comment]
@cpojer Seems I don't have the right to publish a new version, or not sure how to interpret the error message, both npm and yarn fail when trying to publish, the failing uri works fine to get otherwise and certainly exists, but the put to publish fails, so I assume it's because of missing rights:

npm
```
18 http fetch PUT 404 https://registry.npmjs.org/@react-native-community%2fblur 4283ms
19 verbose stack Error: 404 Not Found - PUT https://registry.npmjs.org/@react-native-community%2fblur - Not found
19 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
19 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
20 verbose statusCode 404
21 verbose pkgid @react-native-community/blur@3.4.0
22 verbose cwd /Users/msand/WebstormProjects/react-native-blur
23 verbose Darwin 19.0.0
24 verbose argv "/usr/local/Cellar/node/12.12.0/bin/node" "/usr/local/bin/npm" "publish" "--verbose"
25 verbose node v12.12.0
26 verbose npm  v6.13.0
27 error code E404
28 error 404 Not Found - PUT https://registry.npmjs.org/@react-native-community%2fblur - Not found
29 error 404
30 error 404 '@react-native-community/blur@3.4.0' is not in the npm registry.
31 error 404 You should bug the author to publish it (or use the name yourself!)
32 error 404 Note that you can also install from a
33 error 404 tarball, folder, http url, or git url.
34 verbose exit [ 1, true ]
```

yarn
```
yarn publish
yarn publish v1.19.1
[1/4] Bumping version...
info Current version: 3.4.0
question New version: 3.4.0
[2/4] Logging in...
[3/4] Publishing...
error Couldn't publish package: "https://registry.yarnpkg.com/@react-native-community%2fblur: Not found"
```

**Comment by thedeepanshujain** [comment]
Thanks for merging @cpojer. 
It has been a great experience solving a problem I faced for all fellow developers.

**Comment by Titozzz** [comment]
@msand you are all set now! Please let me know in the future if you have any issues!

**Comment by afestein** [comment]
Thanks for fixing this. Any chance we could get it published to npm soon?

**Comment by msand** [comment]
Sorry forgot about this, published new version now

**Comment by pinguo-zhouwei** [comment]
@msand No new version found on npm

**Comment by msand** [comment]
It's published under @react-native-community/blur rather than react-native-blur

**Pull request merged**
