### PR TITLE
Feat/eightbitlab blurview

### PR DESCRIPTION
**Pull request by Daavidaviid**
# Summary

Trying to make the utilisation of this library easier on Android (ref and hooks doesn't work easily with this library).
Removing the necessity of viewRef on Android AND now the BlurView can have children just like on iOS.

Following this issue recommendations :
https://github.com/react-native-community/react-native-blur/issues/350

### What's required for testing (prerequisites)?
Nothing. I just updated the native library on Android

### What are the steps to reproduce (after prerequisites)?
Just use the library without needing to add viewRef on Android.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [X] I added the documentation in `README.md`
- [X] I mentioned this change in `CHANGELOG.md`
- [X] I updated the typed files (TS and Flow)
- [X] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by farruxx** [comment]
Hello, good job! Tried to use this commit, got error `com.cmcewen.blurview.BlurringView cannot be cast to android.view.ViewGroup`

**Comment by Daavidaviid** [comment]
Hi, could you try to clean the build folders. There are no mention of BlurringView in my branch I think.

**Comment by farruxx** [comment]
Finally, it worked! Thank you!

**Comment by CoenWarmer** [comment]
Hey @Kureev (or any other maintainers), would be great if this could get merged.

**Comment by Kureev** [comment]
I'll try this PR today after work and merge it if everything is fine. 

Many thanks for working on this 🙌

**Comment by kirillzyusko** [comment]
@Daavidaviid thank you for awesome work.
Could you please replace all mentions of `500px-android-blur` to `BlurView` in links in README?
It can be a little confusing if you click on `500px-android-blur` link but see another library :)

**Comment by Daavidaviid** [comment]
Oh I didn't pay attention. It's corrected

**Comment by luisnaranjo733** [comment]
Once this gets merged in, when can we expect a release that contains this feature? This seems like a really impactful feature.

**Comment by kirillzyusko** [comment]
@Kureev Just want to kindly ask about status of this PR.
Have you had a chance to try it?
And one more question: whether is it possible to release a new version on npm as it get merged?

**Comment by Kureev** [comment]
Can confirm that the code works. Example is a bit off, but I will fix it in my follow-up commit.

Great job, and thank you one more time for your contribution!

**Comment by arelstone** [comment]
Would be nice if the version of this package was bumped

**Comment by elan** [comment]
I might be missing something, but when I tried this with React Navigation on Android to blur a `BottomTabBar`, the blur worked properly, but the entire screen was "dimmed".

Doing something like this:

```js
<BlurView
      style={{
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0
      }}
      blurType={'dark'}
      intensity={100}
>
  <BottomTabBar {...this.props} />
</BlurView>
```

**Comment by Frans-L** [comment]
Hey, awesome update!

I may have found a few bugs:

- If you have multiple BlurViews on the same screen, it seems like only the first one is working. 2nd one is not transparent anymore? Maybe it's blurred two times?
 
-  It seems like border-radius is not working.

- With blurType="dark" the entire screen is dimmed. With blurType="light" , it works as expected.

**Comment by Frans-L** [comment]
Hmm... BlurView component drops the performance of the app significantly, even if the blurred component would be tiny.

Could there be a bug that it always blurs the whole screen, but then it shows only the blurred part?
It would explain the bugs that happen when `overflow: hidden` is not set.

**Comment by arelstone** [comment]
I experience this too. I've decided to skip this, even though the designer is really unhappy

**Comment by martinezguillaume** [comment]
@Frans-L @elan I have the same issue even with the current released version (3.4.1). So I don't think it has something to do with this pr

**Comment by elan** [comment]
I was able to work around the full-screen issue I was having by:

1. Using `overlayColor={'transparent'}`
2. Putting a translucent element below the others to perform the darkening.

Putting `borderRadius` and `overflow` of hidden on a container element does work for rounding.

**Comment by elan** [comment]
> to fix your issue, add overflow style property to its parent.

@Frans-L ~ ah yes, you are correct, this also solves the issue 👍

**Comment by Kureev** [comment]
Can you be so kind to follow-up on the docs update and/or compose a separate PR/PRs for any issues you find? I'm not that active in this repo anymore, but I promise to review your changes if you cc me there 🙏

**Comment by wmonecke** [comment]
> I experience this too. I've decided to skip this, even though the designer is really unhappy

This library is not ready for any Android app in production sadly.

**Comment by Frans-L** [comment]
https://github.com/react-native-community/react-native-blur/issues/365

**Pull request merged**
