### PR TITLE
Update BlurringView.java

### PR DESCRIPTION
**Pull request by eladgel**
work with androidx

# Summary

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by IjzerenHein** [comment]
Dude, the pull request title needs to include why this PR is important or what it fixes, not that a file was updated

**Comment by eladgel** [comment]
@IjzerenHein I wrote that in the pull request that it now supports android x

**Comment by darran-kelinske-fivestars** [comment]
This looks like a dupe of this https://github.com/react-native-community/react-native-blur/pull/319

**Comment by msand** [comment]
https://github.com/react-native-community/react-native-blur/pull/321 already merged

**Pull request closed without merging**
