### PR TITLE
update android support library to androidx

### PR DESCRIPTION
**Pull request by OmranElmasry**
# Summary

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by enieber** [comment]
any update?

**Comment by fenglu09** [comment]
any update ?

**Comment by darran-kelinske-fivestars** [comment]
How do we get this merged?

**Comment by msand** [comment]
https://github.com/react-native-community/react-native-blur/pull/321 already merged

**Pull request closed without merging**
